using System;
using System.Collections.Generic;
using System.Text;
using System.Net;
using System.Windows.Forms;
using System.Net.Mail;
using System.Web;
using Outlook = Microsoft.Office.Interop.Outlook;
using System.Diagnostics;
using System.IO;
using System.Globalization;
using AppCode;
using System.Runtime.InteropServices.WindowsRuntime;


namespace TheEmailClass
{
    public static class emailSender
    {
        private static SmtpClient client;
        private static MailMessage msg;

        public static string relMsg = "";
        public static string toMailids = "";
        public static string ccMailids = "";
        public static string mailSubject = "";

        public static string MailHeader = "";
        public static string MailRecipient = "";
        public static string MailBody = "";
        public static string MailSignature = "";

        public static bool IsRevision = false;

        public static DateTime dt = DateTime.Today;

        public static bool sendMailOk = false;

        public static Microsoft.Office.Interop.Outlook.OlImportance imip = Microsoft.Office.Interop.Outlook.OlImportance.olImportanceNormal;

        public static void sendbyOutlook()
        {

            Outlook.Application myMailing;

            try
            {
                if (!IsProcessOpen("OUTLOOK")) //for checking outlook
                {
                    myMailing = new Outlook.Application();
                    Outlook.NameSpace ns = myMailing.GetNamespace("MAPI");
                    Outlook.MAPIFolder f = ns.GetDefaultFolder(Outlook.OlDefaultFolders.olFolderInbox);
                    System.Threading.Thread.Sleep(3000); // test
                }
                else
                {
                    myMailing = new Outlook.Application();
                }

                //Outlook.MailItem myMailingItem = (Outlook.MailItem)myMailing.CreateItem(Outlook.OlItemType.olMailItem);
                Outlook.MailItem myMailingItem = (Outlook.MailItem)myMailing.CreateItem(Outlook.OlItemType.olMailItem);

                myMailingItem.To = toMailids;
                myMailingItem.CC = ccMailids;

                //myMailingItem.To = "Pramod.Maharajan@acero.ae";
                //myMailingItem.CC = "Pramod.Maharajan@acero.ae";

                myMailingItem.Subject = mailSubject;
                myMailingItem.Importance = imip;

                //myMailingItem.Sensitivity = Microsoft.Office.Interop.Outlook.OlSensitivity.olConfidential;

                //myMailingItem.FlagDueBy = dt;
                //myMailingItem.ReminderTime = dt;
                //myMailingItem.ReminderSet = true;
                //string theSig = ReadSignature();

                //string getPersonData = Cart.MakePersonSignature();
                //string noteInMail = "\n\n" + "________________________________________________________________________________\nNOTE : This email is automatically generated by the '[AEM] Acero Engineering module'";

                //myMailingItem.Body = relMsg + "\n\n\nRegards, \n" + getPersonData + noteInMail;
                myMailingItem.HTMLBody = CreateHTMLBody();

                //myMailingItem.BodyFormat = Microsoft.Office.Interop.Outlook.OlBodyFormat.olFormatHTML;
                //myMailingItem.HTMLBody = "<HTML><H2>" + relMsg + "</H2><BODY> \n\n\nRegards, \n" + getPersonData + noteInMail + "</BODY></HTML>";
                //myMailingItem.Display(true);
                //string test = myMailingItem.ItemProperties.Session.Accounts.Application.
                //myMailingItem.Save();

                if (Environment.UserName == Cart.IsTheDeveloper)
                {
                    myMailingItem.Save();
                }
                else
                {
                    myMailingItem.Send();
                }


                imip = Microsoft.Office.Interop.Outlook.OlImportance.olImportanceNormal;

            }
            catch (Exception exp)
            {
                MessageBox.Show("Error: OUTLOOK not working " + exp.Message, "Error::Contact PD_SupportDesk", MessageBoxButtons.OK, MessageBoxIcon.Error);
            }

        }

        private static string CreateHTMLBody()
        {
            string theResultVal = "";

            MailSignature = Cart.MakePersonSignature();

            string theModuleName = "[PST] Production Status module";


            theResultVal = "<html>\r\n\r\n<head>\r\n<meta http-equiv=Content-Type content=\"text/html; charset=windows-1252\">\r\n<meta name=Generator content=\"Microsoft Word 15 (filtered)\">\r\n<style>\r\n<!--\r\n /* Font Definitions */\r\n @font-face\r\n\t{font-family:\"Cambria Math\";\r\n\tpanose-1:2 4 5 3 5 4 6 3 2 4;}\r\n@font-face\r\n\t{font-family:Aptos;}\r\n@font-face\r\n\t{font-family:\"Segoe UI\";\r\n\tpanose-1:2 11 5 2 4 2 4 2 2 3;}\r\n /* Style Definitions */\r\n p.MsoNormal, li.MsoNormal, div.MsoNormal\r\n\t{margin:0in;\r\n\tfont-size:12.0pt;\r\n\tfont-family:\"Aptos\",sans-serif;}\r\np\r\n\t{margin-right:0in;\r\n\tmargin-left:0in;\r\n\tfont-size:12.0pt;\r\n\tfont-family:\"Aptos\",sans-serif;}\r\n.MsoChpDefault\r\n\t{font-size:10.0pt;}\r\n@page WordSection1\r\n\t{size:595.3pt 841.9pt;\r\n\tmargin:1.0in 1.0in 1.0in 1.0in;}\r\ndiv.WordSection1\r\n\t{page:WordSection1;}\r\n-->\r\n</style>\r\n\r\n</head>\r\n\r\n<body lang=en-AE style='word-wrap:break-word'>\r\n\r\n<div class=WordSection1>\r\n\r\n<table class=MsoNormalTable border=0 cellspacing=0 cellpadding=0\r\n style='border-collapse:collapse'>\r\n <tr style='height:38.25pt'>\r\n  <td width=26 valign=top style='width:19.5pt;border-top:solid #704040 1.0pt;\r\n  border-left:solid #704040 6.0pt;border-bottom:solid #704040 1.0pt;border-right:\r\n  none;background:#704040;padding:0in 0in 0in 0in;height:38.25pt'>\r\n  <p class=MsoNormal><b><span style='font-size:14.0pt;font-family:\"Segoe UI\",sans-serif;\r\n  color:#704040'>&nbsp;</span></b></p>\r\n  </td>\r\n  <td width=1812 style='width:1359.35pt;border-top:solid #704040 1.0pt;\r\n  border-left:none;border-bottom:solid #704040 1.0pt;border-right:solid #704040 6.0pt;\r\n  background:#704040;padding:0in 5.4pt 0in 5.4pt;height:38.25pt'>\r\n  <p class=MsoNormal><a name=\"_MailOriginal\"><b><span style='font-size:14.0pt;\r\n  font-family:\"Segoe UI\",sans-serif;color:white'>" +
                                   MailHeader + "</span></b></a><span\r\n  style='color:white'> </span></p>\r\n  </td>\r\n </tr>\r\n <tr style='height:96.6pt'>\r\n  <td width=26 valign=top style='width:19.5pt;border:none;border-left:solid #704040 6.0pt;\r\n  padding:0in 0in 0in 0in;height:96.6pt'>\r\n  <p><span style='color:#156082'>&nbsp;</span></p>\r\n  </td>\r\n  <td width=1812 style='width:1359.35pt;border:none;border-right:solid #704040 6.0pt;\r\n  padding:0in 5.4pt 0in 5.4pt;height:96.6pt'>\r\n  <p><span style='color:#156082'>&nbsp;</span></p>\r\n  <p><span style='font-family:\"Segoe UI\",sans-serif;color:#156082'>" +
                                   MailRecipient + "</span></p>\r\n  <p><span style='font-family:\"Segoe UI\",sans-serif;color:#156082'>&nbsp;</span></p>\r\n  <p><span style='font-family:\"Segoe UI\",sans-serif;color:#156082'>" +
                                   MailBody + " </span></p>\r\n  <p><span style='font-family:\"Segoe UI\",sans-serif;color:#7A4F4F'>&nbsp;</span></p>\r\n  <p><span style='font-family:\"Segoe UI\",sans-serif;color:#156082'>&nbsp;</span></p>\r\n  </td>\r\n </tr>\r\n <tr style='height:48.3pt'>\r\n  <td width=26 valign=top style='width:19.5pt;border:none;border-left:solid #704040 6.0pt;\r\n  padding:0in 0in 0in 0in;height:48.3pt'>\r\n  <p><span style='font-family:\"Segoe UI\",sans-serif;color:#156082'>&nbsp;</span></p>\r\n  </td>\r\n  <td width=1812 style='width:1359.35pt;border:none;border-right:solid #704040 6.0pt;\r\n  padding:0in 5.4pt 0in 5.4pt;height:48.3pt'>\r\n  <p><span style='position:absolute;z-index:251658240'><span style='font-family:\r\n  \"Segoe UI\",sans-serif;color:#156082'>" +
                                   MailSignature + "</span></p>\r\n  </td>\r\n </tr>\r\n <tr style='height:17.9pt'>\r\n  <td width=26 valign=top style='width:19.5pt;border-top:none;border-left:solid #704040 6.0pt;\r\n  border-bottom:solid #704040 1.0pt;border-right:none;padding:0in 0in 0in 0in;\r\n  height:17.9pt'>\r\n  <p><span style='font-family:\"Segoe UI\",sans-serif;color:#156082'>&nbsp;</span></p>\r\n  </td>\r\n  <td width=1812 style='width:1359.35pt;border-top:none;border-left:none;\r\n  border-bottom:solid #704040 1.0pt;border-right:solid #704040 6.0pt;\r\n  padding:0in 5.4pt 0in 5.4pt;height:17.9pt'>\r\n  <p><span style='font-family:\"Segoe UI\",sans-serif;color:#156082'>&nbsp;</span></p>\r\n  </td>\r\n </tr>\r\n <tr style='height:17.1pt'>\r\n  <td width=26 valign=top style='width:19.5pt;padding:0in 0in 0in 0in;\r\n  height:17.1pt'>\r\n  <p align=right style='text-align:right'><span style='font-family:\"Segoe UI\",sans-serif;\r\n  color:#A6A6A6'>&nbsp;</span></p>\r\n  </td>\r\n  <td width=1812 style='width:1359.35pt;padding:0in 5.4pt 0in 5.4pt;height:\r\n  17.1pt'>\r\n  <p align=right style='text-align:right'><i><span style='font-size:11.0pt;\r\n  font-family:\"Segoe UI\",sans-serif;color:#A6A6A6'>This email is automatically\r\n  generated by the '" +
                                   theModuleName + "'</span></i></p>\r\n  </td>\r\n </tr>\r\n</table>\r\n\r\n<p class=MsoNormal>&nbsp;</p>\r\n\r\n</div>\r\n\r\n</body>\r\n\r\n</html>\r\n";


            return theResultVal;

        }

        private static bool IsProcessOpen(string name)
        {
            //here we're going to get a list of all running processes on
            //the computer
            foreach (Process clsProcess in Process.GetProcesses())
            {
                //now we're going to see if any of the running processes
                if (clsProcess.ProcessName.ToString().ToUpper().Contains(name))
                {
                    //if the process is found to be running then we
                    //return a true
                    return true;
                }
            }
            //otherwise we return a false
            return false;
        }

    }
}



